### PR TITLE
Max bugfix

### PR DESCRIPTION
**Pull request by adrianco**
Max needs to return the upper bound of the top bucket to be more than
the actual maximum value seen.

### CODE REVIEW

**Comment by codahale** [comment]
Good find, but this breaks the build. Can you fix the tests?

**Comment by adrianco** [comment]
Sorry, I ended up including my addition to hdr as well as the fix of the test in the same commit

**Comment by codahale** [comment]
No worries — thanks for the fix!

**Comment by adrianco** [comment]
I'm modifying metrics to allow entire distributions to be extracted, not just percentiles. Needed the extra method in hdr. I've got versions for codahale/metrics and for go-kit/metrics.

Thanks for the quick merge!

**Pull request merged**
