### PR TITLE
Added Test for Distribution

### PR DESCRIPTION
**Pull request by adrianco**
Check that Distribution dump has correct length and content.

### CODE REVIEW

**Comment by codahale** [comment]
This appears to be unmergeable.

**Comment by adrianco** [comment]
I think the last update should fix the problem. Also I don't have enough experience with github pull requests to know if I'm using it right...

**Comment by codahale** [comment]
That didn't work. You'll need to make sure the branch you're working off of merges cleanly into a fresh copy of this repo's master.

If you're unfamiliar with Git, [this may help](http://dont-be-afraid-to-commit.readthedocs.org/en/latest/git/conflicts.html).

**Comment by adrianco** [comment]
Found some time to fix this. Looks like a clean add of a new test now.

**Comment by codahale** [comment]
Thanks!

**Pull request merged**
